excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://matlab379.github.io
title: &#23567;&#39321;&#23665;&#21035;&#39302;
tagline: You are here for some resons
description: It's a long way to science & engineering. Anyway, not only sweat but sweet!
paginate: 5